plugins { id 'com.android.application' }
android {
    namespace 'com.techno.installer'
    compileSdk 34
    defaultConfig {
        applicationId "com.techno.installer"
        minSdk 21
        targetSdk 26
        versionCode 18
        versionName "4.3"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
